---
language: python
python: "2.7"
sudo: required
dist: trusty

env:
  - SITE=test.yml

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
 
install:
  # Install Ansible.
  - pip install ansible
  - echo "localhost" > inventory

script:
  # We have a different canonical role name from our github repo
  # in order to accommodate galaxy's naming conventions.
  - "ln -s ../ansible.plone_server ../plone.plone_server"

  # Check the role/playbook's syntax.
  - "ansible-playbook -i inventory $SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i inventory $SITE --connection=local --sudo"
